version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db
  db:
    container_name: stock-server-db
    image: mysql
    volumes:
      - stock_db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  # data-server:
  #   build:
  #     context: ./data-server
  #     args: 
  #       JAR_FILE: stockdata-0.0.1-SNAPSHOT.jar
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   image: stock-data-server:0.0.1
  #   ports:
  #     - "8001:8080"
  #   restart: always

volumes:
  stock_db_volume: {}
networks:
  stock-server-network:
    driver: bridge